### ISSUE TITLE
config

### ISSUE THREAD

**Issue by nsar1907** [jshridha/docker-nzbgetvpn#17]
hello i wanna say thank you for this greatjob!

may you tell me pls what to fill up config file ?

**Comment by jshridha** [comment]
You don't need to fill out the config directory manually. On first boot, it'll populate the config directory and then you'll be able to do the configuration through the webui. Let me know if you don't get it up and running and I'll help you out.

**Comment by nsar1907** [comment]
> You don't need to fill out the config directory manually. On first boot, it'll populate the config directory and then you'll be able to do the configuration through the webui. Let me know if you don't get it up and running and I'll help you out.

i still cant do it :( im sure u would do it in seconds if u connect to my pc via teamviewer etc when you have time. pls let me know when you have time because i tried everything and still doesnt work :/
