### ISSUE TITLE
ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)

### ISSUE THREAD

**Issue by gaiacanon** [jshridha/docker-nzbgetvpn#19]
This is the nzbget portion of my YML

```
  nzbget:
    container_name: nzbget
    image: jshridha/docker-nzbgetvpn:latest
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=${piausername}
      - VPN_PASS=${piapassword}
      - VPN_PROV=pia
      - VPN_REMOTE=France
      - STRICT_PORT_FORWARD=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=209.222.18.222,37.235.1.174,1.1.1.1,8.8.8.8,209.222.18.218,37.235.1.177,1.0.0.1,8.8.4.4
      - DEBUG=true
      - PUID=1008
      - PGID=1004
      - TZ=America/New_York
    volumes:
      - ${storagepath}/nzbget/config:/config
      - /mnt/storage/data/usenet:/data/usenet
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget.rule=Host(`nzb.${domain}`)"
      - "traefik.http.routers.nzbget.entrypoints=traefik-pool"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
    networks:
      - traefik-pool
    restart: unless-stopped
```

This is the error I'm getting:

```
2020-04-10 11:32:31,263 DEBG 'start-script' stdout output:


fo] Starting OpenVPN...




2020-04-10 11:32:31,273 DEBG 'start-script' stdout output:


Fri Apr 10 11:32:31 2020 WARNING: file 'credentials.conf' is group or others accessible


Fri Apr 10 11:32:31 2020 OpenVPN 2.4.7 [git:makepkg/2b8aec62d5db2c17+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019


Fri Apr 10 11:32:31 2020 library versions: OpenSSL 1.1.1b  26 Feb 2019, LZO 2.10




2020-04-10 11:32:31,274 DEBG 'start-script' stdout output:


[info] OpenVPN started




2020-04-10 11:32:31,275 DEBG 'start-script' stdout output:


Fri Apr 10 11:32:31 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]194.99.106.148:1198


Fri Apr 10 11:32:31 2020 UDP link local: (not bound)


Fri Apr 10 11:32:31 2020 UDP link remote: [AF_INET]194.99.106.148:1198




2020-04-10 11:32:31,644 DEBG 'start-script' stdout output:


Fri Apr 10 11:32:31 2020 [f11379dfd8129da0247929042a90b661] Peer Connection Initiated with [AF_INET]194.99.106.148:1198




2020-04-10 11:32:32,896 DEBG 'start-script' stdout output:


Fri Apr 10 11:32:32 2020 ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)


Fri Apr 10 11:32:32 2020 Exiting due to fatal error
```

Some quick Googling lead me to reports of needing to run `openvpn --config server.ovpn` as sudo. I can confirm that by running that command in nzabget's OpenVPN directory connects successfully

**Comment by nsar1907** [comment]
now im getting the same problem. did u find any solution ? @gaiacanon

**Comment by jshridha** [comment]
@gaiacanon Sorry for the delay. Make sure to add:

```yaml
cap_add:
  - NET_ADMIN
```

Give that a shot and then let me know and I'll mark this issue closed.

**Comment by nsar1907** [comment]
> @gaiacanon Sorry for the delay. Make sure to add:
> 
> ```yaml
> cap_add:
>   - NET_ADMIN
> ```
> 
> Give that a shot and then let me know and I'll mark this issue closed.

im rly sorry i dont know where to add it. enviroment on docker or ?

**Comment by jshridha** [comment]
If you're running this with docker-compose, the yaml I posted above would go in your compose file.

If you're running it just by typing in the docker run command, check out the main readme. It shows you where to add that privilege.

**Comment by nsar1907** [comment]
> If you're running this with docker-compose, the yaml I posted above would go in your compose file.
> 
> If you're running it just by typing in the docker run command, check out the main readme. It shows you where to add that privilege.

yes i am running it on docker synology nas and i think im missing something i filled up everything as on read me and container is running but still cant reach the WEB UI maybe because of i changed local port 6666 due 6789 port is in use

and i still dont understand where to run --cap-add=NET_ADMIN  on docker. really sorry to bother you

**Comment by jshridha** [comment]
Sorry but I'm not familiar with synolgy so I can't provide much help here.

**Comment by nsar1907** [comment]
> Sorry but I'm not familiar with synolgy so I can't provide much help here.

okay thank you for everything if you see any tips for me pls let me know.

i made it work!! gonna share it soon for people like me who woould like to use it on Synology nas.

so now how can i make sure that im on VPN? @jshridha

**Comment by jshridha** [comment]
@nsar1907 the iptables are set up so that the container can't access the internet if you're not on the VPN. You can also exec into the container and run `curl ifconfig.me` and make sure the ip address does not match your ip address.
