### ISSUE TITLE
No 7zip

### ISSUE THREAD

**Issue by cawilliamson** [jshridha/docker-nzbgetvpn#2]
Hey there!

Firstly - this docker container is absolutely awesome and saved me a whole heap of iptables pain so thanks for that!

Just a little bit of feedback - the only single problem I have with this container is that it doesn't contain 7zip. It would be nice to get this added (happy to create a pull request if that helps?) to get this added to the install list in the install script.

Cheers

**Comment by jshridha** [comment]
Added 7zip via 2fbe614bd40da1c44238f2ae4001a2a8ce8d38c8
