### ISSUE TITLE
cant categories the download files outside of maindir

### ISSUE THREAD

**Issue by nsar1907** [jshridha/docker-nzbgetvpn#21]
i have created an another sharefolder and maped that directory to the container in the GUI

but when i started the download getting this error on nzbget `-/_unpack: could not create directory :`

anyone has the same problem ?

**Comment by jshridha** [comment]
That sounds like a permissions issue. Make sure that the permissions are set properly for the specified PUID and GUID.

**Comment by nsar1907** [comment]
@jshridha i thought so but PUID and GUID is correct. I also give it root PUID and GUID. Is there any Specific way to map categories on your build?

**Comment by jshridha** [comment]
Can you post screenshots of your configuration in synology showing the docker setup and in nzbget showing the category setup?

**Comment by nsar1907** [comment]
```
docker run -d \
--cap-add=NET_ADMIN \
--device=/dev/net/tun \
--name="nzbget-vpn" \
-v /volume1/nzbget/data:/data \
-v /volume1/docker/nzbget:/config \
-e VPN_ENABLED=yes \
-e VPN_USER=MYEMAIL \
-e VPN_PASS=MYPASSWORD \
-e VPN_PROV=nordvpn \
-e STRICT_PORT_FORWARD=no \
-e ENABLE_PRIVOXY=yes \
-e LAN_NETWORK=192.168.178.1/24 \
-e NAME_SERVERS=8.8.8.8,8.8.4.4 \
-e DEBUG=false \
-e UMASK=00 -e PUID=1026 -e PGID=100 -p 6789:6789 jshridha/docker-nzbgetvpn:latest
```
https://imgur.com/y40Xy5X @jshridha 

/volume1/usenet/ has permission for user PUID=1026 PGID=100

**Comment by jshridha** [comment]
/volume1/usenet does not exist inside of the container. Change your DestDir to "/data"

**Comment by nsar1907** [comment]
https://imgur.com/oGIo25i and then https://imgur.com/QCXbS21 @jshridha

**Comment by jshridha** [comment]
Please see my previous comment. It looks like you didn't change the DestDir in nzbget to /data.

Alternatively, you can just make it blank and it'll default to "/data"

**Comment by nsar1907** [comment]
> Please see my previous comment. It looks like you didn't change the DestDir in nzbget to /data.
> 
> Alternatively, you can just make it blank and it'll default to "/data"

sorry for missunderstanding. https://imgur.com/WKQqfuQ

still getting the same error. i also try this `/volume1/nzbget/data/`

**Comment by jshridha** [comment]
Show me the nzbget logs after you changed the DestDir to /data

**Comment by nsar1907** [comment]
> Show me the nzbget logs after you changed the DestDir to /data

https://pastebin.com/mXiqmcs0

**Comment by jshridha** [comment]
```
Thu May  7 00:36:14 2020	ERROR	Could not create directory /volume1/usenet/X-Men.Dark.Phoenix.2019.German.AC3MD.TS.x264-HELD-franky007 -/_unpack: could not create directory : 
Thu May  7 00:36:14 2020	DETAIL	Downloading X-Men.Dark.Phoenix.2019.German.AC3MD.TS.x264-HELD-franky007 -/X-Men.Dark.Phoenix.2019.German.AC3MD.TS.x264-HELD.part02.rar [7/131] @ secure.eu.thundernews.com (secure.eu.thundernews.com)
Thu May  7 00:36:14 2020	DETAIL	Downloading X-Men.Dark.Phoenix.2019.German.AC3MD.TS.x264-HELD-franky007 -/X-Men.Dark.Phoenix.2019.German.AC3MD.TS.x264-HELD.part02.rar [8/131] @ secure.eu.thundernews.com (secure.eu.thundernews.com)
Thu May  7 00:36:14 2020	DETAIL	Downloading X-Men.Dark.Phoenix.2019.German.AC3MD.TS.x264-HELD-franky007 -/X-Men.Dark.Phoenix.2019.German.AC3MD.TS.x264-HELD.part02.rar [9/131] @ secure.eu.thundernews.com (secure.eu.thundernews.com)
Thu May  7 00:36:14 2020	INFO	Unrar: UNRAR 5.70 freeware      Copyright (c) 1993-2019 Alexander Roshal
Thu May  7 00:36:14 2020	INFO	Unrar: Extracting from X-Men.Dark.Phoenix.2019.German.AC3MD.TS.x264-HELD.part01.rar
Thu May  7 00:36:14 2020	INFO	Unrar: Cannot create /volume1/usenet/X-Men.Dark.Phoenix.2019.German.AC3MD.TS.x264-HELD-franky007 -/_unpack/X-Men.Dark.Phoenix.2019.German.AC3MD.TS.x264-HELD/held-xdarkph.mkv
```

It looks like somewhere you still have some setting that is pointing to /volume1/usenet. You shouldn't have to manually set any directories. It should automatically point to /data, so you  may want to just delete your config directory and start again from scratch since you have some stray setting that is causing you issues.

**Comment by jshridha** [comment]
Alternatively, just go through all of your settings and make sure none of them point to /volume1. That directory _does not_ exist for nzbget. It only exists on the host.

**Comment by nsar1907** [comment]
> Alternatively, just go through all of your settings and make sure none of them point to /volume1. That directory _does not_ exist for nzbget. It only exists on the host.

yea but like i say on tittle that i wanna catgegorie the downloded content in an another sharefolder (specific user has RW permission) for plex and to  keep them in order

if i dont use categories then i can find the donwloaed content in data/completed your build works perfect for me expect categories

**Comment by jshridha** [comment]
Right, and I'm giving you instructions on how to do that. You don't need to set any directories to /volume1/anything.

It seems like you're pretty new to docker so I'll explain how it works. The files will download to /data _inside_ the docker. This is mapped to /volume1/usenet _outside_ the docker on your synology. If you specify /volume1/anything inside the docker, it doesn't know where those directories are. Instead, you just set up the category and leave the DestDir blank. It'll automatically put that category in the right place.

**Comment by nsar1907** [comment]
> Right, and I'm giving you instructions on how to do that. You don't need to set any directories to /volume1/anything.
> 
> It seems like you're pretty new to docker so I'll explain how it works. The files will download to /data _inside_ the docker. This is mapped to /volume1/usenet _outside_ the docker on your synology. If you specify /volume1/anything inside the docker, it doesn't know where those directories are. Instead, you just set up the category and leave the DestDir blank. It'll automatically put that category in the right place.

yes u are right it will be in data/movies. so is there any way to give it directories to move catagories to another shared folders ?

**Comment by jshridha** [comment]
You have to map another directory from synology into the docker container. Add the volume mount to your docker run: ```-v /volume1/usenet:/usenet \```

And then change DestDir to /usenet

**Comment by nsar1907** [comment]
> /usenet

it has been worked! thank you so much and sorry to bother you with my newbie

**Comment by jshridha** [comment]
No problem, glad you got it working.
