### ISSUE TITLE
Issues with PIA

### ISSUE THREAD

**Issue by paulwitt** [jshridha/docker-nzbgetvpn#23]
It seems that changes made by PIA on their end are preventing openvpn from connecting.  Are you still maintaining this repo?

**Comment by jshridha** [comment]
All you need to do is update your ovpn file with the new ones from PIA. I'll have to add in some log messages so people know to do that.

**Comment by jshridha** [comment]
Logging info now in master branch and should prompt user to get the newest config from PIA.
