### ISSUE TITLE
Unable to successfully download PIA json to generate token from URL

### ISSUE THREAD

**Issue by DemosKadi** [jshridha/docker-nzbgetvpn#25]
Hey,
when I'm trying to run the container I'm getting this warning 

`2021-04-10 23:31:59,280 DEBG 'start-script' stdout output:`
`[warn] Unable to successfully download PIA json to generate token from URL 'https://10.0.0.1/authv3/generateToken'`
`[info] 3 retries left`
`[info] Retrying in 10 secs...`
over and over again and can't connect to the web ui.
I tried changing the server and reinstalled the container too, but the problem still stands
Do you have any further ideas how this could be fixed?

Logfile:
[supervisord.log](https://github.com/jshridha/docker-nzbgetvpn/files/6290805/supervisord.log)

**Comment by MikeOG444** [comment]
Same issue for me, seems to have started sometime after April 2, 2021

**Comment by MikeOG444** [comment]
@DemosKadi  I changed from CA_Montreal to De_berlin and restarted the container and its working again

**Comment by DemosKadi** [comment]
Just tried it sadly still doesn't work. I tried nehterlands, berlin, frankfurt and denmark but non of them worked

**Comment by JoA-MoS** [comment]
Binhex images had the same issue the solution is there. But in short remove the existing ovpn configuration files and replace with updated from pia

**Comment by jshridha** [comment]
Yes, sounds like outdated ovpn config files. Feel free to reopen if you still have the issue.
