### ISSUE TITLE
Outdated root certificate store and Docker image

### ISSUE THREAD

**Issue by snyssen** [jshridha/docker-nzbgetvpn#29]
Hi,
I had some issues connecting with SSL to my news server and discovered this was because they were using a Let's Encrypt certificate, and the root certificate store provided with your image was outdated and was not accepting said Let's Encrypt certificate.
I made [a fork of your repos](https://github.com/snyssen/docker-nzbgetvpn) and fixed this issue. While I was at it, I also created a GitHub workflow so it automatically build and pushes Docker images to Docker hub every time a push is made on the master branch.
Would you like me to create a pull request to your repos ?

**Comment by jshridha** [comment]
Yes, please! How are the docker image tags determined?

**Comment by snyssen** [comment]
It is the first I tried using GitHub Actions, so to be honest I am not entirely sure what I have done haha. I just took one of the ready made templates and tweaked it so it works with this project. Currently, it seems to create images with the following name and tag: `<GitHub_username>/<GitHub_repos>:<branch_name>`, so in my case the final image was [`snyssen/docker-nzbgetvpn:master`](https://hub.docker.com/layers/175315433/snyssen/docker-nzbgetvpn/master/images/sha256-513fdb756f7114227bef67c5914e3ac7b8db45722248c0587c79d882f9dd3f90?context=repo). From what I can gather the tag is defined using the [ `docker/metadata-action` GitHub action](https://github.com/docker/metadata-action), so simply tweaking that step should be enough to change the final tag.
Also note that in order to use the GitHub action you will have to generate an access token for your Docker Hub account, and then input your Docker username and previously generated token under the `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` GitHub secrets respectively.

**Comment by JoA-MoS** [comment]
@jshridha If you are interested I am the maintainer of @semantic-release-plus/docker a semantic release plugin for automatically releasing docker images based on semantic commit history. I would be happy to set it up for you and give you an overview.

https://www.npmjs.com/package/@semantic-release-plus/docker

**Comment by jshridha** [comment]
@JoA-MoS Thanks, I'll let you know. For now I'm going to try to stick to github actions.

**Comment by jshridha** [comment]
New images should be up on docker hub! Thanks again for the help @snyssen
