### ISSUE TITLE
libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cawilliamson** [jshridha/docker-nzbgetvpn#3]
Hi there!

Looks like the latest nzbet build you're using is built using openssl 1.1 and the Arch-based container you're using uses openssl 1.0. Resulting error is:

`/usr/bin/nzbget: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

Thanks

**Comment by dogtoe** [comment]
My friend and I are both having the same issue.

**Comment by jshridha** [comment]
I'm working on a fix. For the time being, fall back to the jshridha/docker-nzbgetvpn:v18.0_2.3.9-46 container rather than the latest.

**Comment by dogtoe** [comment]
Thank you very much!!!

**Comment by cawilliamson** [comment]
@jshridha Great news that you're working on a fix. One thing to note though is the label v18.0_2.3.9-46 doesn't seem to negotiate a TLS session with my Usenet providers for me. Even without a preferred cipher set I get "TLS handshake failed"

Strangely when downgrading to the previous label (v17*) it did work but obviously due to downgrading NZBGet to a previous version of itself a lot of the functionality didn't work.

**Comment by jshridha** [comment]
I just pushed a new build that should address the openssl issues. @cawilliamson can you check the latest tag in about 10 minutes after the build is complete for your issue? If that doesn't work, please open a new issue for your error.

**Comment by dogtoe** [comment]
Update is working. Thank!!!!

**Comment by jshridha** [comment]
Closing this issue as solved.
