### ISSUE TITLE
Install Python and current version of NZBget stable 18.1

### ISSUE THREAD

**Issue by rubylaser** [jshridha/docker-nzbgetvpn#4]
First of all, thanks for this.  I'm trying this vs. ls.io's NZBget docker to use my PIA VPN.  I'm struggling to use this though because all of my post-processing scripts are failing due to the lack of Python being available.  Could you include this as almost all of the scripts require it?  Here's the error I see.

```
PasswordDetector: /usr/bin/env: ‘python’: No such file or directory 
```

As a test I docker exec'd into the machine and manually installed Python 2.7 and most of my scripts are working now (pacman -S python2).

Also, I assume this is a repository issue, but is it possible to get the latest stable (18.1) instead of 18.0?

One final thing... I see this in my docker logs -f nzbgetvpn
```
PIA incoming port is not an integer, downloads will be slow, does PIA remote gateway supports port forwarding?
````

Is this an issue?  My download speeds seem normal.

Thanks again!

**Comment by rubylaser** [comment]
Sorry, I see that you stuck with 18.0 because of OpenSSL issues.  Hopefully this can be sorted out.  This is an awesome blend of NZBget and OpenVPN.

**Comment by jshridha** [comment]
Added python2 and updated nzbget to 18.1 via 70d3c5af89edd123e4749976ee04d0d27fc006cc.
