### ISSUE TITLE
Remote Mapping with Radarr/Sonarr

### ISSUE THREAD

**Issue by akizzle** [jshridha/docker-nzbgetvpn#5]
How do you get around with running binhex/archrtorrentvpn and jshridha/docker-nzbgetvpn at the same time on the same machine? Looks like we can't use the /data/ for remote mapping for both. I've tried renaming the /data/ folder to /dataz/ but no luck running into some issues. 

nzbget.conf(55): Invalid value for option "TempDir" (/dataz/tmp): could not crea                             te directory :
nzbget.conf(52): Invalid value for option "QueueDir" (/dataz/queue): could not c                             reate directory :
nzbget.conf(46): Invalid value for option "NzbDir" (/dataz/nzb): could not creat                             e directory :

**Comment by KhaaliTurbo** [comment]
What's the user you're running the jshridha/docker-nzbgetvpn container with? It doesn't appear to be running as the default root user as that user can create most folders in the root of the host.
What have you defined as "--pid=[user]" when running the container?
What folder are you mapping the container's /dataz/ folder to on the host?
Looks like a "standard" permissions error.

Run: id <user you have defined/running as>
Then check for the permissions with "ls -al [mapped folder on host]" and look at the dot source value for allowed permissions.

**Comment by nsar1907** [comment]
im having the same problem and found this after check permissions on ssh

```
root@DS218:/volume1/Data/Downloads/data/completed/Series# ls -al

total 0
drwxrwxr-x 1 nzbget media 58 May  9 06:22 .
drwxrwxr-x 1 nzbget media 12 May  9 05:55 ..
drwxrwxr-x 1 nzbget media 72 May  9 06:26 Westworld.S03E08.WEB.h264-TBS

root@DS218:/volume1/Data/Downloads/data/completed/Series/Westworld.S03E08.WEB.h264-TBS# ls -al

total 403864
drwxrwxr-x 1 nzbget media        72 May  9 06:26 .
drwxrwxr-x 1 nzbget media        58 May  9 06:22 ..
-rw-rw-r-- 1 nzbget media 413555489 May  4 03:20 d346a862a76347949a83f53b00aeb26c.mkv
```

i give the right permissions by chown -R and

` find -type f -exec chmod 664 '{}' ';'` `-type d -exec chmod 775 '{}' ';'` 

but the downloaded file gets a different RW permissions after has been download by the container. or mabe im wrong ? 

maybe we need a script as this guys [made ](https://forum.nzbget.net/viewtopic.php?t=835)just for 0644 for files and 0775 for folders ? @jshridha
