### ISSUE TITLE
ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19) 

### ISSUE THREAD

**Issue by Itsmmai** [jshridha/docker-nzbgetvpn#6]
Hi, I'm trying to get your docker file working but somehow I keep ketting this error:

2018-09-22 18:45:07,943 DEBG 'start-script' stdout output:                                               
Sat Sep 22 18:45:07 2018 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)          
Sat Sep 22 18:45:07 2018 Exiting due to fatal error  

I use the latest version in combination with PIA. 

Can you help me?
Kind regards,
Ab

**Comment by Itsmmai** [comment]
Ow and when starting the /root/init.sh I get more then once an error: You must be root.. 

2018-09-22 18:50:51,907 DEBG 'start-script' stderr output:                                               
iptables v1.6.2:                                                                                         
2018-09-22 18:50:51,909 DEBG 'start-script' stderr output:                                               
can't initialize iptables table `filter': Permission denied (you must be root)                           
2018-09-22 18:50:51,910 DEBG 'start-script' stderr output:     

Again... thanks.
Ab

**Comment by jshridha** [comment]
Make sure you're running the docker in privileged mode, or better yet, run it with the net admin capability. Add this to your docker run command:

```
--cap-add=NET_ADMIN
```

**Comment by Itsmmai** [comment]
Any suggestion how to do this on a synology nas?

Groet,
Ab

**Comment by jshridha** [comment]
There should be an option to set privileges under the edit docker container setting. I don't have a Synology so I can't give you more specific instructions, but check this site:
https://www.synology.com/en-global/knowledgebase/DSM/help/Docker/Docker

**Comment by Itsmmai** [comment]
It works now. you have to add /dev/net/tun on you Synology first (so not only on the docker file). That does the trick. (and the high privileges)

**Comment by nsar1907** [comment]
> It works now. you have to add /dev/net/tun on you Synology first (so not only on the docker file). That does the trick. (and the high privileges)

Hello thank you for this feedback. May i ask that if your build works as intended on Synology?
