### ISSUE TITLE
Disappointed in speed

### ISSUE THREAD

**Issue by Itsmmai** [jshridha/docker-nzbgetvpn#7]
Hi, I'm really disappointed in the speed of PIA and Airvpn. I want to try others and I hear great things of ExpressVPN. Is it possible to connect to this provider with you service ?

Thanks in advance,
Ab

**Comment by jshridha** [comment]
Yeah it is possible. All you need to do is place the .ovpn file in the openvpn folder and the container will take care of the rest. Let me know if you have any issues.
